### ISSUE TITLE
.emacs file

### ISSUE THREAD

**Issue by annagracegriffith** [birkenkrahe/cc100#21]
![image](https://user-images.githubusercontent.com/97771969/151040644-aea6af1c-153e-4b58-8343-1bce5b012b32.png)

**Comment by birkenkrahe** [comment]
Thanks - three issues here: 1) the file must be called .emacs, 2) it must be in the location $HOME so that Emacs can find it when it starts. I don't think that the location you chose here is $HOME.  3) The size of the file is large - about 10 times larger than the file that I asked you to download.

**Comment by birkenkrahe** [comment]
...at the start of the class, with a tool as difficult as Emacs, you get the points for trying!
