### ISSUE TITLE
HW .emacs file

### ISSUE THREAD

**Issue by Hattie-Milligan** [birkenkrahe/cc100#24]
![Screen Shot 2022-01-25 at 12 14 14 PM](https://user-images.githubusercontent.com/97625248/151209955-ba93c585-3bdc-4314-8e85-efa743caa144.png)

**Comment by birkenkrahe** [comment]
The .emacs file is a little large. I wonder why - did you customize the layout? That would explain it because when you change the font or theme, Emacs adds code to the .emacs file.
