### ISSUE TITLE
Phillip Brown

### ISSUE THREAD

**Issue by PhillipBrown3680** [birkenkrahe/cc100#30]
#+TITLE:First Org-file
 #+AUTHOR:Phillip Brown

 * My first Org-mode file

   This Org-mode file prints ~hello world~ and creates a source file
   ~first.c~ that can be compiled and executed on the command line.

   #+begin_src C :main yes :includes stdio.h :tangle first.c :results raw :exports both :comments both
     puts("Hello world");
   #+end_src

   #+RESULTS:
   Hello world

**Comment by birkenkrahe** [comment]
Interestingly, ~string~ in GitHub markdown strikes the word through, while in Emacs Org-mode it changes the font to courier. In GitHub, the corresponding code is `string` .
