### ISSUE TITLE
Victor Noppe First.org and First.c zip files

### ISSUE THREAD

**Issue by tum83** [birkenkrahe/cc100#34]
[VictorNoppe.c.zip](https://github.com/birkenkrahe/cc100/files/7960945/VictorNoppe.c.zip)
[VictorNoppe.org.zip](https://github.com/birkenkrahe/cc100/files/7960946/VictorNoppe.org.zip)

**Comment by birkenkrahe** [comment]
HI Victor - there is only one small mistake in your file: the headline markdown code is `* My first file` and not `*My first file`. The space is required by the parser to pick up on the headline. `*My first file*` by contrast is markdown for bold face, and `*My first file ` is no markdown at all.

**Comment by tum83** [comment]
Thank you i will pay better attention to that in the future.
